# Polymorphism

### Operator Overloading

In [2]:
print(1+2)
print("1"+"2")
print("shlok"*3)

3
12
shlokshlokshlok


In [4]:
print(int.__add__(1,2))

3


In [5]:
print(str.__add__("1","2"))

12


In [7]:
print(str.__mul__("hi",2))

hihi


In [16]:
class complex:#for operator overloading(arithmetic operator)
    def __init__(self,r,i):
        self.real=r
        self.imagenary=i
    def __add__(self,other):
        real=self.real+other.real
        imagenary=self.imagenary+other.imagenary
        return f"{real}+{imagenary}i"
c1=complex(1,4)
c2=complex(3,5)
print(c1+c2)

In [19]:
class A:
    def __init__(self,a):
        self.a=a
    def __gt__(self,other):
        if self.a>other.a:
            return f"{self.a} is greater"
        else:
            return f"{other.a} is greater"
s=A(5)
s1=A(3)
print(s1)

### Method Overloading

Python does not support method overloading by default. If you define multiple methods with the same name, only the latest definition will be used.
python does not support traditional method overloading

In [22]:
class addition:
    def sum(self,a,b):
        return a+b
    def sum(self,a,b,c=2):#default argument
        return a+b+c
o=addition()
print(o.sum(2,3))
print(o.sum(12,35,21))


7
68


In [27]:
class addition:
    def sum(self,a,b):
        return a+b
    def sum(self,*args):#using argument
        sum=0
        for i in args:
            sum=sum+i
        return sum
o=addition()
print(o.sum(2,3))
print(o.sum(12,35,21))


5
68


### Method Overriding(inheritance)

#### SINGLE INHERITANCE

In [29]:
class parent:
    def sleep(self):
        print("sleep at 9")
class child(parent):
    def sleep(self):
        print("sleep at 2")
    def eat(self):
        print("eat at 4")
obj=parent()
obj.sleep()

sleep at 9


In [34]:
class parent:
    def sleep(self):
        print("sleep at 9")
class child(parent):
    def sleep(self):
        print("sleep at 2")
        super().sleep()
    def eat(self):
        print("eat at 4")
obj=child()
obj.sleep()
obj.eat()

sleep at 2
sleep at 9
eat at 4


In [39]:
class parent:
    def sleep(self):
        print("sleep at 9")
class child(parent):
    def wake(self):
        print("wake at 2")
    def eat(self):
        print("eat at 4")
obj=child()
obj.sleep()
obj.eat()
obj.wake()
print(child.mro())
print(parent.mro())

sleep at 9
eat at 4
wake at 2
[<class '__main__.child'>, <class '__main__.parent'>, <class 'object'>]
[<class '__main__.parent'>, <class 'object'>]


#### MULTIPLE INHERITANCE

In [41]:
#MULTIPLE PARENT CLASS AND SINGLE CHILD CLASS
class father:
    def sleep(self):
        print("sleep at 9")
    def swim(self):
        print("swim at 6")
class mother:
    def cook(self):
        print("cook good")
    def sleep(self):
        print("sleep at 10")
class child(father,mother):#j class pela lakhyo hoi tema jase
    def run(self):
        print("run very fast")
obj=child()
obj.sleep()
print(child.mro())

sleep at 9
[<class '__main__.child'>, <class '__main__.father'>, <class '__main__.mother'>, <class 'object'>]


#### MULTILEVEL INHERITANCE

In [46]:
class grandfather:
    def sleep(self):
        print("sleep at 9")
class father(grandfather):
    def swim(self):
        print("swim at 6")
class son(father):
    def eat(self):
        print("eat at 4")
obj=son()
obj.sleep()
obj.swim()
obj.eat()
print(son.mro())

sleep at 9
swim at 6
eat at 4
[<class '__main__.son'>, <class '__main__.father'>, <class '__main__.grandfather'>, <class 'object'>]


#### HIERARCHICAL INHERITANCE

In [1]:
class parents:
    def display(self):
        print("display from parent")
class child(parents):
    def fun(self):
        print("fun from child class")
class child2(parents):
    def show(self):
        print("show from child2 class")
        
obj=child()
obj.display()
obj.fun()
print(child.mro())
obj2=child2()
obj2.display()
obj2.show()
print(child.mro())

display from parent
fun from child class
[<class '__main__.child'>, <class '__main__.parents'>, <class 'object'>]
display from parent
show from child2 class
[<class '__main__.child'>, <class '__main__.parents'>, <class 'object'>]


In [3]:
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A,B):
    def show(self):
        print("mulitple inheritance child")
class D(C):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C):
    def show2(self):
        print("hierarchical inheritance child 2")
obj=E()
obj.display()
print(D.mro())
print(E.mro())

multiple inheritance class 1
[<class '__main__.D'>, <class '__main__.C'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]
[<class '__main__.E'>, <class '__main__.C'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]


#### CLASSIC DIAMOND PROBLEM

In [4]:
#FIRST SCENARIO
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A):
    def show(self):
        print("mulitple inheritance child")
class D(B):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C,D):
    def show2(self):
        print("hierarchical inheritance child 2")
print(E.mro())

[<class '__main__.E'>, <class '__main__.C'>, <class '__main__.A'>, <class '__main__.D'>, <class '__main__.B'>, <class 'object'>]


In [5]:
#SECOND SCENARIO
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A,B):
    def show(self):
        print("mulitple inheritance child")
class D(A,B):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C,D):
    def show2(self):
        print("hierarchical inheritance child 2")
print(E.mro())

[<class '__main__.E'>, <class '__main__.C'>, <class '__main__.D'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]


In [6]:
#THIRD SCENARIO
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A,B):
    def show(self):
        print("mulitple inheritance child")
class D(B,A):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C,D):
    def show2(self):
        print("hierarchical inheritance child 2")
print(E.mro())

TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B

In [7]:
#FOURTH SCENARIO
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A,B):
    def show(self):
        print("mulitple inheritance child")
class D(A):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C,D):
    def show2(self):
        print("hierarchical inheritance child 2")
print(E.mro())

[<class '__main__.E'>, <class '__main__.C'>, <class '__main__.D'>, <class '__main__.A'>, <class '__main__.B'>, <class 'object'>]


In [8]:
#FIFTH SCENARIO
class A:
    def display(self):
        print("multiple inheritance class 1")
class B:
    def fun(self):
        print("multiple inheritance class 2")
class C(A,B):
    def show(self):
        print("mulitple inheritance child")
class D(B):
    def show1(self):
        print("hierarchical inheritance child 1")
class E(C,D):
    def show2(self):
        print("hierarchical inheritance child 2")
print(E.mro())

[<class '__main__.E'>, <class '__main__.C'>, <class '__main__.A'>, <class '__main__.D'>, <class '__main__.B'>, <class 'object'>]


## ARRAY

In [10]:
import numpy as np
d=range(3)
print(d)

range(0, 3)


In [12]:
import sys
print(sys.getsizeof(d))

48


In [15]:
arr=np.array(42)
print(arr)
print(arr.ndim)
arr1=np.array([42])
print(arr1)
print(arr1.ndim)
arr2=np.array([[42]])
print(arr2)
print(arr2.ndim)
arr3=np.array([[[42]]])
print(arr3)
print(arr3.ndim)

42
0
[42]
1
[[42]]
2
[[[42]]]
3


In [16]:
arr=np.array([[[1,2,3]]])
print(arr)
print(arr.shape)

[[[1 2 3]]]
(1, 1, 3)


In [18]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


In [23]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [24]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [25]:
import numpy as np
arr=np.array([[1,2,3],[4,56]])
print(arr)
print(arr.ndim)
print(arr.shape)

[list([1, 2, 3]) list([4, 56])]
1
(2,)


<ipython-input-25-f0d147b20694>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr=np.array([[1,2,3],[4,56]])


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[3])
print(arr[2:3])

1
4
[3]


In [50]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0][1])
print(arr[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[1 2]
 [4 5]]


In [56]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,0:2,2])#aama ghanu baki chhe haji
print(arr[1,0:2,0:2])

[3 6]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1=arr.reshape(2,3)
print(arr1)

[[1 2 3]
 [4 5 6]]


In [3]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))

<class 'numpy.ndarray'>


### concatinate,split,where,sort

#### concatenate()

In [7]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
a=np.concatenate((arr1,arr2,arr3))
print(a)
type(a)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
a=np.concatenate((arr1,arr2,arr3),axis=1)#axis=0(row),axis=1(column)
print(a)

AxisError: axis 1 is out of bounds for array of dimension 1

In [13]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
a=np.concatenate((arr1,arr2))
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
a=np.concatenate((arr1,arr2),axis=1)
print(a)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
arr1=np.array([[1,2],[3,4],[11,21]])
arr2=np.array([[5,6],[7,8],[39,93]])
a=np.concatenate((arr1,arr2),axis=1)
print(a)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [11 21 39 93]]


#### split()

In [28]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
a=np.array_split(arr1,4)
b=np.array_split(arr1,3)
c=np.array_split(arr1,9)
d=np.array_split(arr1,12)
print(a)
print(b)
print(c)
print(d)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [35]:
arr1=np.array([[1,2],[3,4],[5,6]])
c=np.array_split(arr1,3)
a=np.array_split(arr1,2)
b=np.array_split(arr1,4)
print(a)
print(b)
print(c)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32)]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [39]:
arr1=np.array([[1,2],[3,4],[5,6]])
c=np.array_split(arr1,3,axis=1)
b=np.array_split(arr1,2,axis=1)
print(b)
print("---------")
print(c)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]
---------
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


#### where()

In [41]:
arr=np.array([1,2,3,4,5,3,6])
a=np.where(3==arr)
print(a)
b=np.where(arr%2==0)
print(b)

(array([2, 5], dtype=int64),)
(array([1, 3, 6], dtype=int64),)


In [43]:
arr1=np.array([[1,2],[3,55],[4,3]])
a=np.where(3==arr1)
print(a)#(array([1, 2]---array index, dtype=int64), array([0, 1]---number kya index par chhe, dtype=int64))

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))


In [44]:
arr=np.array([[[1,2,3],[4,5,6],[7,3,9],[10,11,3]]])
a=np.where(3==arr)
print(a)

(array([0, 0, 0], dtype=int64), array([0, 2, 3], dtype=int64), array([2, 1, 2], dtype=int64))


#### sort()

In [46]:
arr=np.array([1,3,5,4,9,39,5,6])
print(np.sort(arr))

[ 1  3  4  5  5  6  9 39]


In [48]:
arr1=np.array([[1,9],[5,2]])
print(np.sort(arr1))

[[1 9]
 [2 5]]


In [53]:
arr1=np.array([[7,9],[5,2]])
a=np.sort(arr1,axis=0)#axis=-1,1(row),axis=0(column)
print(a)

[[5 2]
 [7 9]]


In [58]:
arr1=np.array([[7,9],[5,2]])
a=np.sort(arr1,axis=None)#None-->1D ma convert kari nakhse
print(a)

[2 5 7 9]


In [54]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [57]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [60]:
import abc
dir(abc)

['ABC',
 'ABCMeta',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_abc_init',
 '_abc_instancecheck',
 '_abc_register',
 '_abc_subclasscheck',
 '_get_dump',
 '_reset_caches',
 '_reset_registry',
 'abstractclassmethod',
 'abstractmethod',
 'abstractproperty',
 'abstractstaticmethod',
 'get_cache_token']

In [70]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw(self):
        print("circle")
a=circle()
a.draw()

circle


In [71]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw1(self):
        print("circle")
a=circle()
a.draw1()#draw name ni method nathi atle

TypeError: Can't instantiate abstract class circle with abstract methods draw

In [72]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name=shape_name
    @abstractmethod
    def draw(self):
        pass
class circle(shape):
    def __init__(self):
        super().__init__("circle")
    def draw(self):
        print("circle")
class triangle(shape):
    def __init__(self):
        super().__init__("triangle")
    def draw(self):
        print("triangle")
a=circle()
a.draw()
b=triangle()
b.draw()

circle
triangle


# codes

In [4]:
from abc import ABC,abstractmethod
class Employee(ABC):
    def getemp(self):
        self.id=int(input("enter id"))
        self.name=input("enter name")
        self.salary=int(input("enter salary"))
    def printemp(self):
        print(f"""id:{self.id}
        name:{self.name}
        salary:{self.salary}""")
    def salemp(self):
        return self.salary
    @abstractmethod
    def empid(self):
        pass
class perks(Employee):
    def gets(self):
        self.getemp()
        s=self.salemp()
        self.hrf=s*0.17
        self.pf=s*0.12
        self.dra=s*0.35
    def printperks(self):
        self.printemp()
        print(f"""dra:{self.dra}
        hrf:{self.hrf}
        pf:{self.pf}""")
    def totalp(self):
        

SyntaxError: unexpected EOF while parsing (<ipython-input-4-2fb4eecffee9>, line 29)

In [5]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [6]:
from numpy import random


In [7]:
dir(random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [9]:
x=random.randint(1,15,(3,5))
x

array([[ 6,  6, 10,  7,  2],
       [14,  2, 13,  3, 13],
       [11, 14,  1,  6,  9]])